-- Add bio column to profiles if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'bio') THEN
        ALTER TABLE profiles ADD COLUMN bio TEXT;
    END IF;
END $$;

-- Fix Storage Policies for Avatars
-- Allow authenticated users to update their own avatars
-- We assume the file path contains the user ID or is unique enough. 
-- For simplicity in this app context, we allow authenticated users to UPDATE objects in 'avatars' bucket.
-- Ideally we check (storage.foldername(name))[1] = auth.uid()::text, but standard RLS is tricky with random filenames.
-- Given the filename is generated by client as `${userId}-${Math.random()}.${fileExt}`

CREATE POLICY "Authenticated users can update avatars"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'avatars');

-- Allow delete just in case
CREATE POLICY "Authenticated users can delete avatars"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'avatars');

-- Drop old policies if they conflict (optional safety, usually names differ)
-- DROP POLICY IF EXISTS "Authenticated users can upload avatars" ON storage.objects;
-- Re-create insert if needed, but '20251231236500_create_storage_buckets.sql' likely handled it.
-- Just adding UPDATE/DELETE is safe.
